blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
        # post views
    path('', views.post_list, name='post_list'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
                views.post_detail,
                name='post_detail'),
    path('tag/<slug:tag_slug>/',
        views.post_list, name='post_list_by_tag'),            
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.urls import reverse

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
       def get_queryset(self):
           return super(PublishedManager,
                        self).get_queryset()\
                             .filter(status='published')

class Post(models.Model):

        STATUS_CHOICES = (
            ('draft', 'Draft'),
            ('published', 'Published'),
        )
        title = models.CharField(max_length=250)
        slug = models.SlugField(max_length=250,
                                unique_for_date='publish')
        author = models.ForeignKey(User,
                                    on_delete=models.CASCADE,
                                    related_name='blog_posts')
        body = models.TextField()
        publish = models.DateTimeField(default=timezone.now)
        created = models.DateTimeField(auto_now_add=True)
        updated = models.DateTimeField(auto_now=True)
        status = models.CharField(max_length=10,
                                    choices=STATUS_CHOICES,
                                    default='draft')
        objects = models.Manager() 
        published = PublishedManager() 
        tags = TaggableManager()                           
        class Meta:
            ordering = ('-publish',)
        def __str__(self):
            return self.title
        def get_absolute_url(self):
           return reverse('blog:post_detail',
                          args=[self.publish.year,
                                self.publish.month,
                                self.publish.day, self.slug])
class Comment(models.Model):
       post = models.ForeignKey(Post,
                                on_delete=models.CASCADE,
                                related_name='comments')
       name = models.CharField(max_length=80)
       email = models.EmailField()
       body = models.TextField()
       created = models.DateTimeField(auto_now_add=True)
       updated = models.DateTimeField(auto_now=True)
       active = models.BooleanField(default=True)
       class Meta:
           ordering = ('created',)
       def __str__(self):
           return f'Comment by {self.name} on {self.post}'
# Create your models here.

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
       class Meta:
           model = Comment
           fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from .models import Post,Comment
from .forms import  CommentForm
from django.core.paginator import Paginator, EmptyPage,\
                                     PageNotAnInteger
from taggit.models import Tag                                     



def post_list(request, tag_slug=None):

    posts = Post.published.all()
    object_list = Post.published.all()
    tag = None
    if tag_slug:
           tag = get_object_or_404(Tag, slug=tag_slug)
           object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3) 
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)

    except PageNotAnInteger:
          
            posts = paginator.page(1)
    except EmptyPage:
           
           posts = paginator.page(paginator.num_pages)
    return render(request,
                        'blog/post/list.html',
                        {'page': page,
                            'posts': posts,
                            'tag': tag})

def post_detail(request, year, month, day, post):
       post = get_object_or_404(Post, slug=post,
                                      status='published',
                                      publish__year=year,
                                      publish__month=month,
                                      publish__day=day)
        # List of active comments for this post
       comments = post.comments.filter(active=True)
       new_comment = None
       if request.method == 'POST':
           # A comment was posted
           comment_form = CommentForm(data=request.POST)
           if comment_form.is_valid():
               # Create Comment object but don't save to database yet
               new_comment = comment_form.save(commit=False)
               # Assign the current post to the comment
               new_comment.post = post
               # Save the comment to the database
               new_comment.save()
       else:
           comment_form = CommentForm()                              
       return render(request,
                     'blog/post/detail.html',
                     {'post': post,
                     'comments': comments,
                      'new_comment': new_comment, 
                      'comment_form': comment_form})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
   <!DOCTYPE html>
   <html>
   <head>
     <title>{% block title %}{% endblock %}</title>
     <link href="{% static "css/blog.css" %}" rel="stylesheet">
   </head>
   <body>
     <div id="content">
       {% block content %}
       {% endblock %}
     </div>
     <div id="sidebar">
       <h2>Kemi's blog</h2>
       <p>Welcome to kemi's blog.</p>
       <p>This is my blog. I've written {% total_posts %} posts so far.</p>
         
     </div>
   </body>
   </html>

blog/templates/blog/paginator.html
<div class="pagination">
    <span class="step-links">
      {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
      {% endif %}
      <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
    </span>
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
   {% block title %}{{ post.title }}{% endblock %}
   {% block content %}
     <h1>{{ post.title }}</h1>
     <p class="date">
       Published {{ post.publish }} by {{ post.author }}
     </p>
     {{ post.body|linebreaks }}
     {% with comments.count as total_comments %}
     <h2>
       {{ total_comments }} comment{{ total_comments|pluralize }}
     </h2>
     {% endwith %}
     {% for comment in comments %}
     <div class="comment">
       <p class="info">
         Comment {{ forloop.counter }} by {{ comment.name }}
         {{ comment.created }}
       </p>
       {{ comment.body|linebreaks }}
     </div>
   {% empty %}
     <p>There are no comments yet.</p>
   {% endfor %}
   {% if new_comment %}
     <h2>Your comment has been added.</h2>
   {% else %}
     <h2>Add a new comment</h2>
     <form method="post">
       {{ comment_form.as_p }}
       {% csrf_token %}
       <p><input type="submit" value="Add comment"></p>
     </form>
   {% endif %}

   {% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
   {% block title %}Kemi's Blog{% endblock %}
   

   {% block content %}
     <h1>Kemi's Blog</h1>
     {% if tag %}
       <h2>Posts tagged with "{{ tag.name }}"</h2>
     {% endif %}
     {% for post in posts %}
       <h2>
         <a href="{{ post.get_absolute_url }}">
           {{ post.title }}
           
         </a>
       </h2>
       <p class="tags">
         Tags:
        {% for tag in post.tags.all %}
          <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
            {{ tag.name }}
          </a>
          {% if not forloop.last %}, {% endif %}
        {% endfor %}
 
         
       </p>
       {{ post.body|truncatewords:30|linebreaks }}
     {% endfor %}
     {% include "pagination.html" with  page=posts %}
   {% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
      {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
      {% endif %}
      <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
    </span>
</div>